name: Deploy Portfolio

on:
  push:
    paths:
      - "apps/portfolio/**"
      - "packages/**"
      - "tsconfig.base.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Pull Vercel project settings
        run: |
          npx vercel pull \
            --cwd apps/portfolio \
            --yes \
            --token ${{ secrets.VERCEL_TOKEN }}

      - name: Patch tsconfig for Vercel build
        run: |
          cp tsconfig.base.json apps/portfolio/tsconfig.base.json
          sed -i 's|"extends": "../../tsconfig.base.json"|"extends": "./tsconfig.base.json"|' apps/portfolio/tsconfig.json

      - name: Deploy to Vercel (server-side build)
        run: |
          npx vercel deploy \
            --cwd apps/portfolio \
            --prod \
            --yes \
            --token ${{ secrets.VERCEL_TOKEN }}
